/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ObdButton {
    'block': boolean;
    'type': string;
  }
  interface ObdButtonArrow {
    'right': boolean;
  }
  interface ObdCard {
    'cardSubtitle': string;
    'cardTitle': string;
  }
  interface ObdModal {
    'active': boolean;
    'maxWidth': string;
    'modalSubtitle': string;
    'modalTitle': string;
  }
  interface ObdPageNotFound {
    'emoji': string;
    'message': string;
    'status': string;
  }
  interface ObdScroll {
    'target': string;
  }
  interface ObdTable {
    'actions': string;
    'columns': string;
    'data': string;
    'layout': string;
  }
  interface ObdTableMenu {
    'meals': string;
  }
}

declare global {


  interface HTMLObdButtonElement extends Components.ObdButton, HTMLStencilElement {}
  var HTMLObdButtonElement: {
    prototype: HTMLObdButtonElement;
    new (): HTMLObdButtonElement;
  };

  interface HTMLObdButtonArrowElement extends Components.ObdButtonArrow, HTMLStencilElement {}
  var HTMLObdButtonArrowElement: {
    prototype: HTMLObdButtonArrowElement;
    new (): HTMLObdButtonArrowElement;
  };

  interface HTMLObdCardElement extends Components.ObdCard, HTMLStencilElement {}
  var HTMLObdCardElement: {
    prototype: HTMLObdCardElement;
    new (): HTMLObdCardElement;
  };

  interface HTMLObdModalElement extends Components.ObdModal, HTMLStencilElement {}
  var HTMLObdModalElement: {
    prototype: HTMLObdModalElement;
    new (): HTMLObdModalElement;
  };

  interface HTMLObdPageNotFoundElement extends Components.ObdPageNotFound, HTMLStencilElement {}
  var HTMLObdPageNotFoundElement: {
    prototype: HTMLObdPageNotFoundElement;
    new (): HTMLObdPageNotFoundElement;
  };

  interface HTMLObdScrollElement extends Components.ObdScroll, HTMLStencilElement {}
  var HTMLObdScrollElement: {
    prototype: HTMLObdScrollElement;
    new (): HTMLObdScrollElement;
  };

  interface HTMLObdTableElement extends Components.ObdTable, HTMLStencilElement {}
  var HTMLObdTableElement: {
    prototype: HTMLObdTableElement;
    new (): HTMLObdTableElement;
  };

  interface HTMLObdTableMenuElement extends Components.ObdTableMenu, HTMLStencilElement {}
  var HTMLObdTableMenuElement: {
    prototype: HTMLObdTableMenuElement;
    new (): HTMLObdTableMenuElement;
  };
  interface HTMLElementTagNameMap {
    'obd-button': HTMLObdButtonElement;
    'obd-button-arrow': HTMLObdButtonArrowElement;
    'obd-card': HTMLObdCardElement;
    'obd-modal': HTMLObdModalElement;
    'obd-page-not-found': HTMLObdPageNotFoundElement;
    'obd-scroll': HTMLObdScrollElement;
    'obd-table': HTMLObdTableElement;
    'obd-table-menu': HTMLObdTableMenuElement;
  }
}

declare namespace LocalJSX {
  interface ObdButton {
    'block'?: boolean;
    'type'?: string;
  }
  interface ObdButtonArrow {
    'right'?: boolean;
  }
  interface ObdCard {
    'cardSubtitle'?: string;
    'cardTitle'?: string;
  }
  interface ObdModal {
    'active'?: boolean;
    'maxWidth'?: string;
    'modalSubtitle'?: string;
    'modalTitle'?: string;
    'onClosed'?: (event: CustomEvent<any>) => void;
  }
  interface ObdPageNotFound {
    'emoji'?: string;
    'message'?: string;
    'status'?: string;
  }
  interface ObdScroll {
    'target'?: string;
  }
  interface ObdTable {
    'actions'?: string;
    'columns'?: string;
    'data'?: string;
    'layout'?: string;
    'onAction'?: (event: CustomEvent<any>) => void;
  }
  interface ObdTableMenu {
    'meals'?: string;
    'onDelete'?: (event: CustomEvent<any>) => void;
    'onEdit'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'obd-button': ObdButton;
    'obd-button-arrow': ObdButtonArrow;
    'obd-card': ObdCard;
    'obd-modal': ObdModal;
    'obd-page-not-found': ObdPageNotFound;
    'obd-scroll': ObdScroll;
    'obd-table': ObdTable;
    'obd-table-menu': ObdTableMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'obd-button': LocalJSX.ObdButton & JSXBase.HTMLAttributes<HTMLObdButtonElement>;
      'obd-button-arrow': LocalJSX.ObdButtonArrow & JSXBase.HTMLAttributes<HTMLObdButtonArrowElement>;
      'obd-card': LocalJSX.ObdCard & JSXBase.HTMLAttributes<HTMLObdCardElement>;
      'obd-modal': LocalJSX.ObdModal & JSXBase.HTMLAttributes<HTMLObdModalElement>;
      'obd-page-not-found': LocalJSX.ObdPageNotFound & JSXBase.HTMLAttributes<HTMLObdPageNotFoundElement>;
      'obd-scroll': LocalJSX.ObdScroll & JSXBase.HTMLAttributes<HTMLObdScrollElement>;
      'obd-table': LocalJSX.ObdTable & JSXBase.HTMLAttributes<HTMLObdTableElement>;
      'obd-table-menu': LocalJSX.ObdTableMenu & JSXBase.HTMLAttributes<HTMLObdTableMenuElement>;
    }
  }
}


