/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ObdButton {
    'block': boolean;
    'type': string;
  }
  interface ObdCard {
    'cardSubtitle': string;
    'cardTitle': string;
  }
  interface ObdModal {
    'active': boolean;
    'modalSubtitle': string;
    'modalTitle': string;
  }
  interface ObdTable {
    'actions': string;
    'columns': string;
    'data': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLObdButtonElement extends Components.ObdButton, HTMLStencilElement {}
  var HTMLObdButtonElement: {
    prototype: HTMLObdButtonElement;
    new (): HTMLObdButtonElement;
  };

  interface HTMLObdCardElement extends Components.ObdCard, HTMLStencilElement {}
  var HTMLObdCardElement: {
    prototype: HTMLObdCardElement;
    new (): HTMLObdCardElement;
  };

  interface HTMLObdModalElement extends Components.ObdModal, HTMLStencilElement {}
  var HTMLObdModalElement: {
    prototype: HTMLObdModalElement;
    new (): HTMLObdModalElement;
  };

  interface HTMLObdTableElement extends Components.ObdTable, HTMLStencilElement {}
  var HTMLObdTableElement: {
    prototype: HTMLObdTableElement;
    new (): HTMLObdTableElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'obd-button': HTMLObdButtonElement;
    'obd-card': HTMLObdCardElement;
    'obd-modal': HTMLObdModalElement;
    'obd-table': HTMLObdTableElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface ObdButton {
    'block'?: boolean;
    'type'?: string;
  }
  interface ObdCard {
    'cardSubtitle'?: string;
    'cardTitle'?: string;
  }
  interface ObdModal {
    'active'?: boolean;
    'modalSubtitle'?: string;
    'modalTitle'?: string;
    'onClosed'?: (event: CustomEvent<any>) => void;
  }
  interface ObdTable {
    'actions'?: string;
    'columns'?: string;
    'data'?: string;
    'onAction'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'obd-button': ObdButton;
    'obd-card': ObdCard;
    'obd-modal': ObdModal;
    'obd-table': ObdTable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'obd-button': LocalJSX.ObdButton & JSXBase.HTMLAttributes<HTMLObdButtonElement>;
      'obd-card': LocalJSX.ObdCard & JSXBase.HTMLAttributes<HTMLObdCardElement>;
      'obd-modal': LocalJSX.ObdModal & JSXBase.HTMLAttributes<HTMLObdModalElement>;
      'obd-table': LocalJSX.ObdTable & JSXBase.HTMLAttributes<HTMLObdTableElement>;
    }
  }
}


