/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ObdButton {
    'type': string;
  }
  interface ObdCard {
    'cardSubtitle': string;
    'cardTitle': string;
  }
  interface ObdInput {
    'label': string;
    'type': string;
    'value': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLObdButtonElement extends Components.ObdButton, HTMLStencilElement {}
  var HTMLObdButtonElement: {
    prototype: HTMLObdButtonElement;
    new (): HTMLObdButtonElement;
  };

  interface HTMLObdCardElement extends Components.ObdCard, HTMLStencilElement {}
  var HTMLObdCardElement: {
    prototype: HTMLObdCardElement;
    new (): HTMLObdCardElement;
  };

  interface HTMLObdInputElement extends Components.ObdInput, HTMLStencilElement {}
  var HTMLObdInputElement: {
    prototype: HTMLObdInputElement;
    new (): HTMLObdInputElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'obd-button': HTMLObdButtonElement;
    'obd-card': HTMLObdCardElement;
    'obd-input': HTMLObdInputElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface ObdButton {
    'type'?: string;
  }
  interface ObdCard {
    'cardSubtitle'?: string;
    'cardTitle'?: string;
  }
  interface ObdInput {
    'label'?: string;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'type'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'obd-button': ObdButton;
    'obd-card': ObdCard;
    'obd-input': ObdInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'obd-button': LocalJSX.ObdButton & JSXBase.HTMLAttributes<HTMLObdButtonElement>;
      'obd-card': LocalJSX.ObdCard & JSXBase.HTMLAttributes<HTMLObdCardElement>;
      'obd-input': LocalJSX.ObdInput & JSXBase.HTMLAttributes<HTMLObdInputElement>;
    }
  }
}


